datasets:
  adamson: "src/data/adamson/perturb_processed.h5ad"
  dixit: "src/data/dixit/perturb_processed.h5ad"
  norman: "src/data/norman/perturb_processed.h5ad"
embeddings:
  emb_a: "src/data/Data_GeneEmbd/ensem_emb_gpt3.5all_new.pickle"
  emb_b: "src/data/Data_GeneEmbd/GenePT_gene_embedding_ada_text.pickle"
  emb_c: "src/data/Data_GeneEmbd/GPT_3_5_gene_embeddings.pickle"
  emb_d: "src/data/Data_GeneEmbd/GenePT_gene_protein_embedding_model_3_text.pickle"
scgpt_pretrained_root: "artifacts/models/scGPT_human"
